version:
  jquery: 3.1.1
  semantic_ui: 2.2.9
  font_awesome: 4.7.0
  moment: 2.17.1
  count_up: 1.8.1
  js_cookie: 2.1.3
  echarts: 3.4.0

google_analytics_id: UA-33449675-7
piwik_analytics_site_id: 1

repository: https://github.com/caiguocn/Jinbu

timezone: Asia/Shanghai

name: 进步英语
author: iROCKBUNNY 步步
author_url: http://www.ejinbu.com
organization: EJinbu
organization_url: http://ejinbu.com
description: 进步英语
keywords: 进步听力学英语, 英语, 听力, 四级英语考试, 新概念英语, 六级英语, 托福,雅思,
url: http://www.ejinbu.com
contact: QQ:2650908450  或者 QQ 4577047

logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

gems:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
